// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TheAside: typeof import('./src/components/layout/TheAside.vue')['default']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
  }
}

export { }
